import mongoose from "mongoose";
import bcrypt from "bcrypt";

// destructuring
const { Schema, model } = mongoose;

// making user schema
const userSchema = new Schema(
  {
    // id will be generated by mongodb by their own and we can use that id as _id
    username: {
      type: String,
      required: [true, "Username is required"],
      unique: true,
      minLength: [6, "minimun 6 character needed"],
      maxLength: [50],
      lowercase: true,
      trim: true,
      index: true,
    },
    email: {
      type: String,
      required: [true, "Email is required"],
      unique: true,
      lowercase: true,
      trim: true,
    },
    fullName: {
      type: String,
      required: [true, "Fullname is required"],
      minLength: [3, "minimun 3 character needed"],
      maxLength: [50],
      lowercase: true,
      trim: true,
    },
    password: {
      type: String,
      required: [true, "Password is required"],
      trim: true,
    },
    avatar: {
      type: String, // cloudinary url
    },
    refreshToken: {
      type: String,
    },
  },
  {
    // timestamps is used to create two field mainly 1. createdAt and 2. updatedAt
    timestamps: true,
  }
);

// it just hash the password before saving it to database so that no one is able to see the actual password.
userSchema.pre("save", async function (req, res, next) {
  if (!this.isModified("password")) return next();

  this.password = await bcrypt.hash(this.password, 10);
});

// here we compare the original password and hashedPassword so that we can decide whether the user is genuine or not.
userSchema.methods.isPasswordCorrect = async function (req, res, next) {
  return await bcrypt.compare(password, this.password);
};

// exporting userSchema
export const User = model("User", userSchema);
